### ISSUE TITLE
Add an attachment support

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/request-reply-component#7]
In some scenarios, it makes sense to get an attachment in a reply message.

**Comment by jhorbulyk** [comment]
## Recommendations on how to complete in Sprint 43:
Create a new action `replyWithAttachment`. In the default `reply` action, metadata.in has the following three properties: `contentType`, `responseBody`, `statusCode` and a special `InMetadataExtensionView` config field for creating headers.  This new action should have the same special view for headers as well as inputs for `contentType` and `satusCode` but instead of accepting a string `responseBody`, it should expect a string `responseUrl`. The response URL should be an http url to a steward attachment.

The new action should read the contents of the steward attachment and stream it to maester in the expected encription format. It should then formulate a message that is sent to the `reply` queue that has the same structure that is send from `reply-lightweight` (with the Maester reference changed).  

Reference for sample code to create appropreately formated Maester attachments: https://github.com/elasticio/elasticio/issues/4101#issuecomment-644533217

**Comment by drobiazko** [comment]
@jhorbulyk I don't understand how an integrator would know know what to type into the field `responseUrl`. Can you elaborate on that please? Another question I have is if this proposal is considered as a temporal fix for a project or as a global component available to everyone?

**Comment by jhorbulyk** [comment]
> I don't understand how an integrator would know know what to type into the field responseUrl. Can you elaborate on that please?

Consider the following use case:
An integrator wants to create an HTTP request/reply flow where given a query string paramater in the URL, the flow will respond with different image files from an SFTP server in the reply.  The integrator would build the flow as follows:

1. For the first step create a webhook component with a query string parameter.
2. For the second step, use the SFTP component's **Download File by name** action. Build the file path with the info from step 1.  This component will return a message with a steward attachment that is referenced in the body:
![ksnip_20200623$](https://user-images.githubusercontent.com/5710732/85387100-b2c6d480-b544-11ea-96a3-1c574b64895c.png)
3. For the third step, the integrator would select the **Reply** component and then the **Reply with Attachment** option.  When the user is presented with the three input metadata fields described in this issue, they would complete them as follows:
* **Status Code** - Hardcoded JSONata constant of `200`
* **Content Type** - Hardcoded JSONata constant of `application/png` or perhaps a more complex JSONata mapping where the content type is dynamically built dependant on the extension of the file retrieved from SFTP.
* **Response URL** - JSONata expression that is matched to the `attachment_url` property of the incoming message from SFTP.

>  Another question I have is if this proposal is considered as a temporal fix for a project or as a global component available to everyone?

The proposal here is a new action on the reply component that will be globally available to everyone.

**Comment by drobiazko** [comment]
Why don't we let SFTP upload the file directly into Maester and reuse the new logic from https://github.com/elasticio/request-reply-component/pull/19

**Comment by jhorbulyk** [comment]
> Why don't we let SFTP upload the file directly into Maester and reuse the new logic from #19

Breaking this down in to two parts:

## Why don't we let SFTP upload the file directly into Maester
Migrating from using Steward to store attachments to using Maester to store attachments is definetly  a sensible suggestion.  For increased visibility, it is probably better to make that suggestion in either Product Board or as it's own GitHub Issue, not as a comment in another issue. A couple things that we need to be careful of for this approach. There are lots of existing components that read & write attachments from Steward. They can all be re-written in such a way so that they all have the capacity to also read attachments from Maester. However, Maester URLs are not backwards compatible with Steward URLs (Maester has added encryption & additional authentication parameters). This means that we will have to update the read capacity for every single attachment consuming component before writing Maester (unless we are willing to throw away components or introduce integrators to two types of attachments).  Additional, to the best of my knowledge Maester has not been generally released and so customers/white label partners who write their own components that interact with attachments will not be able to make Maester compatible components at this time.

## Why don't we use the logic from #19 
Some limiations of the logic in #19 :
* The solution in 19 provides no mechanism to set the HTTP status code of the response
* The solution in 19 provides no mechanism to set the content-type or other HTTP headers of the response
* The solution in 19 requires that the component immediately proceeding the reply to provide output in a completely novel format.
* The solution in 19 provides no mechanism to select only a single part of the data in the accumulated flow to return (e.g. at attachment produced two steps prior)

**Comment by drobiazko** [comment]
# Why don't we let SFTP upload the file directly into Maester

Recently we introduced a feature of fixing component versions in flows. We also migrated all the existing flows so that we have not a single flow using `latest` component version, unless it was set by an integrator explicitly. One of the key advantages of fixing component versions is the possibility to introduce backward incompatible changes to components without braking existing flows. This approach is similar to fixing library versions from NPM - every upgrade of a component library has a potential to break your app and so needs to be tested. That's why it is ok to migrate SFTP to Maester and few other components consuming attachments that are required for a particular project.

Maester is already deployed to our production and may be considered as production ready. The only missing part to make it generally available is  to adopt this new technology. If our own team is not willing to adopt it, why shall the others do it? 

# Regarding the limitations in #19

* no mechanism to set the HTTP status code of the response: very easy to introduce
* no mechanism to set the content-type or other HTTP headers of the response: very easy to introduce
* the component immediately proceeding the reply to provide output in a completely novel format: addressed with fixed component versions (see above)
* no mechanism to select only a single part of the data in the accumulated flow to return (e.g. at attachment produced two steps prior): do we have a requirement for that at all? If so, it can be implemented with Maester as well

**Comment by jhorbulyk** [comment]
> The only missing part to make it generally available is to adopt this new technology.

An additional **significant** hinderance is the lack of any documentation that is available to our partners/customers.

> That's why it is ok to migrate SFTP to Maester and few other components consuming attachments that are required for a particular project.

I agree that this is an excellent suggestion. @drobiazko Can you write up an insight/item in Product Board?

**Comment by jhorbulyk** [comment]
Starting point in branch `reply-with-attachment`

**Comment by denyshld** [comment]
Proposed implementation includes data copying from Steward  attachments Maester to which uses additional resources.

Webhook changes from platform side means that we need improvement to read attachments from Steward in webhhok side, which is not possible now.

Copying means data replication between Steward and Maester. Anyway, it will be changed when we moved platform attachments on Maester.

So, to provide appropriate implementation we should wait for EIO platform side changes:
https://app.zenhub.com/workspaces/elasticio-59cb79abd6a2a75883931c56/issues/elasticio/elasticio/1456

**Comment by A3a3e1** [comment]
POC so far: https://github.com/elasticio/request-reply-component/tree/reply-with-attachment

**Comment by A3a3e1** [comment]
@jhorbulyk Could you pls update the requirements (user-story, definition of done) for the task?
As the latest description has been done 1.5 years ago https://github.com/elasticio/request-reply-component/issues/7#issuecomment-648028188

**Comment by jhorbulyk** [comment]
# Requirements for PS Sprint 63
Same as here: https://github.com/elasticio/request-reply-component/issues/7#issuecomment-646681470

## Sample Flow Use Case
I should be able to create the following flow:
1. Step One: Webhook Receive: which expects a GET request with a queryString parameter `fileName`
2. Step 2: SFTP Lookup File Name By File: which pulls a .png file from an SFTP server based on the name provided by `fileName`
3. HTTP Reply: Pull the steward attachment URL from step 2. Set status code to `200` & content type `image/png`.

End result is thaw when the flow is running and one visits the flow URL in a web browser, the browser should render the png file.

**Comment by EmptyInfinity** [comment]
@jhorbulyk I was able to render a .pdf and .txt  with this component. But there is some problems with .png rendering. Now waiting for help from firefighters.
